services:
  db:
    image: postgres:16
    container_name: carrierwave_cdn_gcs_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d

